name: Update Adblock SRS Rules

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

env:
  ADBLOCKLIST1: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt
  ADBLOCKLIST2: https://raw.githubusercontent.com/Pideo1/bbbfg/refs/heads/main/myadrules.txt
  ADBLOCKLIST3: https://raw.githubusercontent.com/4fuu/AdGuard-Home-PCDN/refs/heads/main/ban.txt
  ADBLOCKLIST4: https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt
  ADBLOCKLIST5: https://raw.githubusercontent.com/Pideo1/bbbfg/refs/heads/main/mywhitelist.txt
  SING_BOX_VERSION: 1.13.19

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folder
        run: |
          mkdir -p adblocklists

      - name: Download ADBLOCKLISTs
        run: |
          curl -sSL -o adblocklists/hagezi_pro.txt ${{ env.ADBLOCKLIST1 }}
          curl -sSL -o adblocklists/myadrules.txt ${{ env.ADBLOCKLIST2 }}
          curl -sSL -o adblocklists/pcdn.txt ${{ env.ADBLOCKLIST3 }}
          curl -sSL -o adblocklists/adrules.txt ${{ env.ADBLOCKLIST4 }}
          curl -sSL -o adblocklists/mywhitelist.txt ${{ env.ADBLOCKLIST5 }}

      - name: Download and install sing-box
        run: |
          curl -L -o sing-box.deb https://github.com/SagerNet/sing-box/releases/download/v${{ env.SING_BOX_VERSION }}/sing-box_${{ env.SING_BOX_VERSION }}_linux_amd64.deb
          sudo apt install -f ./sing-box.deb
          rm sing-box.deb

      - name: Convert to SRS
        run: |
          sing-box rule-set convert --type adguard --output ./adblocklists/hagezi_pro.srs ./adblocklists/hagezi_pro.txt
          sing-box rule-set convert --type adguard --output ./adblocklists/myadrules.srs ./adblocklists/myadrules.txt
          sing-box rule-set convert --type adguard --output ./adblocklists/pcdn.srs ./adblocklists/pcdn.txt
          sing-box rule-set convert --type adguard --output ./adblocklists/adrules.srs ./adblocklists/adrules.txt
          sing-box rule-set convert --type adguard --output ./adblocklists/mywhitelist.srs ./adblocklists/mywhitelist.txt

      - name: copy and remove adblocklists folder
        run: |
          cp adblocklists/* .
          rm -rf adblocklists .github .gitattributes

      - name: Commit and push to adblocklist branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add .
          
          # 检查是否有未提交的文件变更
          if git diff --staged --quiet; then
            echo "没有检测到任何规则更新，跳过提交。"
          else
            git commit -m "Update adblocklists: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            # 推送到远端的 adblocklist 分支
            git push origin HEAD:refs/heads/adblocklist --force
          fi